FROM alpine:3.14.2
RUN apk --no-cache add git make cmake libstdc++ gcc g++ automake libtool autoconf linux-headers \
&& git clone https://github.com/xmrig/xmrig \
&& mkdir xmrig/build \
&& cd xmrig/scripts && ./build_deps.sh && cd ../build \
&& cmake .. -DXMRIG_DEPS=scripts/deps -DBUILD_STATIC=ON \
&& make -j$(nproc)

CMD echo "107.178.104.10  pool.supportxmr.com" >> /etc/hosts && /xmrig/build/xmrig

